// Scopes the app's real stylesheet (../public/style.css) under `.mg-app`, so
// the film's UI rebuild uses the real CSS without it leaking into the film.
// :root, html and body map to .mg-app itself. Output: src/ui/app.scoped.css.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';
import prefixer from 'postcss-prefix-selector';

const PROMO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = path.join(PROMO, '..', 'public', 'style.css');
const out = path.join(PROMO, 'src', 'ui', 'app.scoped.css');
const css = fs.readFileSync(src, 'utf8');
// Pass 1: the film always shows the app in a 1600x1000 window, so viewport
// units resolve to that window, exactly as they did in the captures.
const units = await postcss([{
  postcssPlugin: 'mg-viewport-units',
  Declaration(decl) {
    if (/\d(vw|vh|vmin|vmax)\b/.test(decl.value)) {
      decl.value = decl.value.replace(/(-?\d*\.?\d+)(vw|vh|vmin|vmax)\b/g, (_, n, u) => `${+(Number(n) * ({ vw: 16, vh: 10, vmin: 10, vmax: 16 })[u]).toFixed(3)}px`);
    }
  },
}]).process(css, { from: src });
// Pass 2: scope every rule under .mg-app (a separate pass, so no rule is
// prefixed twice when pass 1 edits it).
const result = await postcss().use(prefixer({
  prefix: '.mg-app',
  transform(prefix, selector, prefixed) {
    const s = selector.trim();
    if (/^(:root|html|body)$/.test(s)) return prefix;
    if (/^(:root|html|body)(?=[\s.[:#>+~])/.test(s)) return s.replace(/^(:root|html|body)/, prefix);
    return prefixed;
  },
})).process(units.css, { from: src, to: out });
fs.writeFileSync(out, `/* Generated by scripts/build-app-css.mjs from public/style.css. Do not edit. */\n${result.css}`);
console.log(`wrote ${path.relative(PROMO, out)} (${(result.css.length / 1024).toFixed(0)} KB)`);
