// Scopes the app's real stylesheet (../public/style.css) under `.mg-app`, so
// the film's UI rebuild uses the real CSS without it leaking into the film.
// :root, html and body map to .mg-app itself. Output: src/ui/app.scoped.css.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';
import prefixer from 'postcss-prefix-selector';

const PROMO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = path.join(PROMO, '..', 'public', 'style.css');
const out = path.join(PROMO, 'src', 'ui', 'app.scoped.css');
const css = fs.readFileSync(src, 'utf8');
const result = await postcss().use(prefixer({
  prefix: '.mg-app',
  transform(prefix, selector, prefixed) {
    const s = selector.trim();
    if (/^(:root|html|body)$/.test(s)) return prefix;
    if (/^(:root|html|body)(?=[\s.[:#>+~])/.test(s)) return s.replace(/^(:root|html|body)/, prefix);
    return prefixed;
  },
})).process(css, { from: src, to: out });
fs.writeFileSync(out, `/* Generated by scripts/build-app-css.mjs from public/style.css. Do not edit. */\n${result.css}`);
console.log(`wrote ${path.relative(PROMO, out)} (${(result.css.length / 1024).toFixed(0)} KB)`);
